// Browser-only checks: controls, focus, displayed quest state, route buttons, art.
// Quest rules, combat, rewards and persistence are exercised through MCP scenarios.
const assert = require('node:assert/strict');
const path = require('node:path');
const { chromium, STUB } = require('./lib/playwright.cjs');
const { Client } = require('@modelcontextprotocol/sdk/client/index.js');
const { StdioClientTransport } = require('@modelcontextprotocol/sdk/client/stdio.js');
const root = path.resolve(__dirname, '..');
const client = new Client({ name: 'valhallasc-ui-check', version: '1.0.0' });
let browser, started = false, checks = 0;
const check = (condition, message) => { assert.ok(condition, message); checks++; };
async function call(name, args = {}) {
  const result = await client.callTool({ name, arguments: args });
  assert.ok(!result.isError, `${name}: ${JSON.stringify(result.content)}`);
  return result.structuredContent;
}
(async () => {
  const transport = new StdioClientTransport({ command: process.execPath, args: [path.join(root, 'scripts/test-mcp.cjs')], cwd: root, stderr: 'pipe' });
  await client.connect(transport);
  const world = await call('start_world'); started = true;
  browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => localStorage.setItem('valhallasc.save.v1', JSON.stringify({ lang: 'en', sound: false, char: null, draft: null })));
  await page.goto(world.url); await page.locator('#start').click(); await page.locator('#login-guest').click();
  await page.locator('#cls-warrior').click(); await page.locator('#name').fill('QuestUI');
  await page.locator('#go').click({ timeout: 60000 });
  await page.waitForFunction(() => Online.connected && !!Field.warriorSprites && !!Field.beetleSprites, null, { timeout: 60000 });
  check(await page.locator('#quest-tracker').textContent().then(t => t.includes('Speak to Wren')), 'HUD introduces the first quest');
  await page.keyboard.press('q');
  check(await page.locator('#quest-journal').isVisible(), 'Q opens the journal');
  check(await page.locator('#quest-list .quest-card').count() === 17, 'All seventeen quests display across both zones');
  check(await page.locator('#quest-close').evaluate(n => n === document.activeElement), 'Journal takes keyboard focus');
  await page.keyboard.press('Tab');
  check(await page.locator('#quest-list button').first().evaluate(n => n === document.activeElement), 'Tab wraps within the journal');
  await page.keyboard.press('Shift+Tab');
  check(await page.locator('#quest-close').evaluate(n => n === document.activeElement), 'Shift+Tab wraps within the journal');
  check(await page.locator('#quest-list [data-quest="king_challenge"]').textContent().then(t => t.includes('Locked') && t.includes('Shells of Steel')), 'Locked cards explain their prerequisite');
  check(await page.locator('#quest-list [data-quest="king_challenge"] .quest-level').textContent() === 'Recommended level 5'
    && await page.locator('#quest-list [data-quest="welcome"] .quest-level').textContent() === 'Recommended level 1', 'Every journal card shows its recommended level');
  await page.screenshot({ path: path.join(world.artifacts, 'quest-journal.png') });
  await page.keyboard.press('Escape');
  check(await page.locator('#quest-journal').isHidden(), 'Escape closes the journal');
  await page.locator('#quest-tracker').click();
  check(await page.locator('#quest-journal').isVisible(), 'HUD button opens the journal');
  await page.locator('#quest-list [data-quest="welcome"] button').filter({ hasText: 'Get quest from Wren' }).click();
  await page.locator('#npc-dialogue').waitFor({ state: 'visible', timeout: 60000 });
  check(await page.locator('#npc-name').textContent() === 'Wren', 'Journal travel button reaches and opens the giver');
  check(await page.locator('#quest-journal').isHidden(), 'Travel closes the journal');
  await page.locator('#npc-quests [data-quest="welcome"] [data-action="accept"]').click();
  await page.waitForFunction(() => document.getElementById('npc-notice').textContent.includes('Quest accepted'));
  check(await page.locator('#npc-quests [data-quest="welcome"]').textContent().then(t => t.includes('In progress')), 'NPC card reflects accepted state');
  await page.locator('#npc-close').click();
  await page.waitForFunction(() => document.getElementById('quest-tracker').textContent.includes('Speak to Sister Elara: 0/1'));
  check(await page.locator('.tracker-quest[data-quest="welcome"] .tracker-objective').count() === 3, 'Tracker gives each objective its own indented line');
  const trackerBounds = await page.locator('#quest-tracker').boundingBox();
  check(trackerBounds.x > 720, 'Objective tracker sits on the right side of the world');
  await page.getByRole('button', { name: 'Collapse quest tracker' }).click();
  check(await page.locator('.tracker-list').isHidden(), 'Quest tracker collapses without opening the journal');
  await page.getByRole('button', { name: 'Expand quest tracker' }).click();
  check(await page.locator('.tracker-list').isVisible(), 'Collapsed tracker can be expanded');
  check(await page.evaluate(() => Quests.marker('healer') === '◆'), 'NPC quest objective marker is active');
  await page.keyboard.press('q');
  const welcome = page.locator('#quest-list [data-quest="welcome"]');
  await welcome.locator('button').filter({ hasText: 'Track quest', exact: true }).click();
  check(await welcome.locator('button').filter({ hasText: 'Tracking', exact: true }).isVisible(), 'Track button shows the selection');
  await page.keyboard.press('Escape');
  await page.evaluate(() => Field.visitNpc('healer'));
  await page.locator('#npc-dialogue').waitFor({ state: 'visible', timeout: 30000 });
  await page.keyboard.press('Escape'); await page.keyboard.press('q');
  await page.waitForFunction(() => document.querySelector('#quest-list [data-quest="welcome"]').textContent.includes('Speak to Sister Elara: 1/1'));
  check(await welcome.textContent().then(t => t.includes('Speak to Bram: 0/1')), 'Journal displays authoritative partial progress');
  await page.screenshot({ path: path.join(world.artifacts, 'quest-progress.png') });
  await page.keyboard.press('Escape');
  check(await page.locator('.tracker-objective.complete').count() === 1, 'Completed objectives are visibly marked in green');
  // Display-only ledger fixture checks multiple objectives without forging combat.
  const fixture = await browser.newPage({ viewport: { width: 1440, height: 900 }, bypassCSP: true });
  await fixture.goto(new URL('health', world.url).href);
  await fixture.setContent('<main id="stage" class="stage" data-scene="game"><section id="quest-tracker" class="quest-tracker"></section><div id="quest-journal" hidden><div id="quest-list"></div><button id="quest-close"></button></div><div id="pause" hidden></div><div id="equipment" hidden></div></main>');
  await fixture.addStyleTag({ path: path.join(root, 'client/style.css') });
  await fixture.addStyleTag({ path: path.join(root, 'client/online.css') });
  await fixture.addScriptTag({ path: path.join(root, 'client/world.js') });
  await fixture.evaluate(() => { window.Online = { connected: true }; window.Field = { hero: { dead: false }, setPaused: () => {} }; window.City = { open: false }; });
  await fixture.addScriptTag({ path: path.join(root, 'client/quests.js') });
  await fixture.evaluate(() => Quests.update([{ id: 'welcome', counts: [1, 0, 0], claimed: false, completions: 0 }, { id: 'slime_patrol', counts: [2], claimed: false, completions: 0 }, { id: 'meadow_bounty', counts: [8], claimed: false, completions: 0 }]));
  check(await fixture.locator('.tracker-quest').count() === 3, 'Tracker displays all active quests together');
  check(await fixture.locator('.tracker-quest[data-quest="meadow_bounty"] .complete').textContent().then(t => t.includes('Return to Linden')), 'Completed quests display their turn-in destination');
  await fixture.screenshot({ path: path.join(world.artifacts, 'quest-tracker.png') });
  check(await page.evaluate(stub => !!Field.warriorSprites.source.parts.body && (stub || Field.beetleSprites.img.beetle.complete), STUB), 'Character and enemy artwork load');
  check(errors.length === 0, `No browser runtime errors: ${errors.join('; ')}`);
  console.log(`${checks} focused quest UI checks passed; screenshots: ${world.artifacts}`);
})().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => {
  await browser?.close();
  if (started) await call('stop_world').catch(() => {});
  await client.close();
});
